version: "3.8"
services:
  
  app:
    container_name: simple_django_restApi_app
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn books.wsgi:application --bind 0.0.0.0:8000 && python manage.py makemigrations && python manage.py migrate
    volumes:
      - .:/opt/services/books/src
    ports:
      - 5001:8000
    # networks:
        # - coding_postgresql_default
# networks:
    # coding_postgresql_default:
      # external: true
