# Generated by Django 4.1.2 on 2022-12-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"managed": False},
        ),
    ]
